import { afterEach, describe, expect, it, vi } from "vitest";

import {
  isLandPointer,
  normalizeDeployment,
  normalizeDeployments,
  type RawDeployment,
} from "./discover-deployed";
import { discoverDeployedScenes } from "./discover-deployed.server";

const BASE = "https://catalyst.example.com";

const landComposite: RawDeployment = {
  entityId: "bafkland1",
  entityType: "scene",
  pointers: ["-86,78"],
  entityTimestamp: 300,
  localTimestamp: 301,
  content: [
    { key: "main.composite", hash: "bafcomposite1" },
    { key: "assets/images/autogenerated-thumbnail.png", hash: "bafthumb1" },
    { key: "models/thing.glb", hash: "bafglb1" },
    { key: "scene.json", hash: "bafscene1" },
  ],
  metadata: {
    display: { title: "UAP", navmapThumbnail: "assets/images/autogenerated-thumbnail.png" },
    scene: { base: "-86,78" },
  },
};

const worldScene: RawDeployment = {
  entityId: "bafworld1",
  entityType: "scene",
  pointers: ["mycoolworld.dcl.eth"],
  entityTimestamp: 200,
  content: [{ key: "main.composite", hash: "bafcompositeW" }],
  metadata: {
    display: { title: "My World" },
    worldConfiguration: { name: "mycoolworld.dcl.eth" },
  },
};

const codeOnly: RawDeployment = {
  entityId: "bafcode1",
  entityType: "scene",
  pointers: ["10,10"],
  entityTimestamp: 400,
  content: [
    { key: "bin/index.js", hash: "bafjs1" },
    { key: "scene.json", hash: "bafscene2" },
  ],
  metadata: { display: { title: "Code Scene" }, scene: { base: "10,10" } },
};

const profileJunk: RawDeployment = {
  entityId: "bafprofile1",
  entityType: "profile",
  pointers: ["0x7bbea9c18cd0541acab8c19da2b11d0c03faef1c"],
  content: [],
  metadata: { avatars: [] },
};

const landCompositeDup: RawDeployment = { ...landComposite, pointers: ["-86,78", "-85,78"] };

describe("isLandPointer", () => {
  it("treats parcel coordinates as land and names as world", () => {
    expect(isLandPointer("-86,78")).toBe(true);
    expect(isLandPointer("0,0")).toBe(true);
    expect(isLandPointer("mycoolworld.dcl.eth")).toBe(false);
    expect(isLandPointer("0x7bbea9c18cd0541acab8c19da2b11d0c03faef1c")).toBe(false);
  });
});

describe("normalizeDeployment", () => {
  it("classifies a land composite scene as editable land with the right href + thumbnail", () => {
    const s = normalizeDeployment(landComposite, BASE)!;
    expect(s).not.toBeNull();
    expect(s.kind).toBe("land");
    expect(s.editable).toBe(true);
    expect(s.republishable).toBe(true);
    expect(s.title).toBe("UAP");
    expect(s.baseParcel).toBe("-86,78");
    expect(s.worldName).toBeNull();
    expect(s.deployedAt).toBe(300);
    expect(s.openHref).toBe("/creator-hub/scene-editor?pointer=-86%2C78&from=discovery");
    expect(s.thumbnailUrl).toBe(`${BASE}/content/contents/bafthumb1`);
  });

  it("classifies a world scene: kind=world, baseParcel=worldName, world=1 in href", () => {
    const s = normalizeDeployment(worldScene, BASE)!;
    expect(s.kind).toBe("world");
    expect(s.worldName).toBe("mycoolworld.dcl.eth");
    expect(s.baseParcel).toBe("mycoolworld.dcl.eth");
    expect(s.editable).toBe(true);
    expect(s.republishable).toBe(true);
    expect(s.openHref).toBe(
      "/creator-hub/scene-editor?pointer=mycoolworld.dcl.eth&world=1&from=discovery",
    );
    expect(s.thumbnailUrl).toBeNull();
  });

  it("marks a code-only scene (no main.composite) as not editable", () => {
    const s = normalizeDeployment(codeOnly, BASE)!;
    expect(s.kind).toBe("land");
    expect(s.editable).toBe(false);
    expect(s.title).toBe("Code Scene");
  });

  it("drops non-scene (profile) deployments", () => {
    expect(normalizeDeployment(profileJunk, BASE)).toBeNull();
  });

  it("drops deployments with no entityId", () => {
    expect(normalizeDeployment({ entityType: "scene", pointers: ["0,0"] }, BASE)).toBeNull();
  });

  it("falls back to 'Untitled scene' when no title is present", () => {
    const s = normalizeDeployment(
      { entityId: "x", entityType: "scene", pointers: ["1,1"], content: [] },
      BASE,
    )!;
    expect(s.title).toBe("Untitled scene");
  });
});

describe("normalizeDeployments (dedup + sort)", () => {
  const scenes = normalizeDeployments(
    [codeOnly, worldScene, landComposite, landCompositeDup, profileJunk],
    BASE,
  );

  it("drops the profile and dedups by entityId", () => {
    expect(scenes.map((s) => s.entityId)).toEqual(["bafkland1", "bafworld1", "bafcode1"]);
  });

  it("sorts editable-first, then newest deployedAt", () => {
    expect(scenes.map((s) => s.title)).toEqual(["UAP", "My World", "Code Scene"]);
  });
});

describe("discoverDeployedScenes (mocked transport)", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  const page = (deployments: RawDeployment[], next?: string) =>
    new Response(JSON.stringify({ deployments, pagination: next ? { next } : {} }), {
      status: 200,
      headers: { "content-type": "application/json" },
    });

  it("lowercases the address, paginates, re-asserts entityTypes, dedups", async () => {
    const urls: string[] = [];
    const fetchImpl = vi.fn(async (url: string) => {
      urls.push(String(url));
      if (urls.length === 1) {
        return page([landComposite, worldScene], "?deployedBy=addr&lastId=bafworld1&limit=100");
      }
      return page([codeOnly, landCompositeDup]);
    });
    vi.stubGlobal("fetch", fetchImpl);

    const scenes = await discoverDeployedScenes("0x7BBEA9C18Cd0541ACab8C19DA2b11D0C03FAEF1C");

    expect(fetchImpl).toHaveBeenCalledTimes(2);
    expect(urls[0]).toContain("/content/deployments?");
    expect(urls[0]).toContain("deployedBy=0x7bbea9c18cd0541acab8c19da2b11d0c03faef1c");
    expect(urls[0]).toContain("entityTypes=scene");
    expect(urls[1]).toContain("entityTypes=scene");
    expect(scenes.map((s) => s.entityId)).toEqual(["bafkland1", "bafworld1", "bafcode1"]);
  });

  it("returns [] on a total network failure (never throws)", async () => {
    const fetchImpl = vi.fn(async () => {
      throw new Error("connection refused");
    });
    vi.stubGlobal("fetch", fetchImpl);
    await expect(discoverDeployedScenes("0xabc")).resolves.toEqual([]);
  });

  it("returns [] for a blank address without fetching", async () => {
    const fetchImpl = vi.fn();
    vi.stubGlobal("fetch", fetchImpl);
    await expect(discoverDeployedScenes("   ")).resolves.toEqual([]);
    expect(fetchImpl).not.toHaveBeenCalled();
  });
});
