// Generated by scripts/gen-scene-analytics-zod.mts -- do not edit.
// Source of truth: catalyrst/ui3/src/creatorhub/lib/scene-analytics.ts (camelCase model).
// Wire = snake_cased model, nullable fields defaulting to null, arrays to [].
// Regenerate: npm run gen:scene-analytics (drift-gated by scene-analytics.gen.test.ts).
import { z } from "zod";
import type {
  SceneMetricsWindow,
  SceneRetention,
  SceneRetentionPoint,
  SceneDailyStats,
  SceneStats,
  CreatorScenesStats,
} from "@ui/creatorhub/lib/scene-analytics";

const WireSceneTypeSchema = z.enum(["genesis", "world"]);

const WireSceneMetricsWindowSchema = z.object({
  users: z.number().nullable().default(null),
  new_users: z.number().nullable().default(null),
  returning_users: z.number().nullable().default(null),
  visits: z.number().nullable().default(null),
  median_active_time_s: z.number().nullable().default(null),
  total_active_hours: z.number().nullable().default(null),
  afk_time_pct: z.number().nullable().default(null),
  peak_concurrent_users: z.number().nullable().default(null),
  median_fps: z.number().nullable().default(null),
  perf_sessions: z.number().nullable().default(null),
  dau: z.number().nullable().default(null),
  desktop_users: z.number().nullable().default(null),
  mobile_users: z.number().nullable().default(null),
  messages_sent: z.number().nullable().default(null),
  emotes_played: z.number().nullable().default(null),
  avg_session_active_time_s: z.number().nullable().default(null),
});

function toSceneMetricsWindow(w: z.infer<typeof WireSceneMetricsWindowSchema>): SceneMetricsWindow {
  return {
    users: w.users,
    newUsers: w.new_users,
    returningUsers: w.returning_users,
    visits: w.visits,
    medianActiveTimeS: w.median_active_time_s,
    totalActiveHours: w.total_active_hours,
    afkTimePct: w.afk_time_pct,
    peakConcurrentUsers: w.peak_concurrent_users,
    medianFps: w.median_fps,
    perfSessions: w.perf_sessions,
    dau: w.dau,
    desktopUsers: w.desktop_users,
    mobileUsers: w.mobile_users,
    messagesSent: w.messages_sent,
    emotesPlayed: w.emotes_played,
    avgSessionActiveTimeS: w.avg_session_active_time_s,
  };
}

const WireSceneRetentionSchema = z.object({
  cohort: z.number().nullable().default(null),
  d1: z.number().nullable().default(null),
  d7: z.number().nullable().default(null),
  d30: z.number().nullable().default(null),
});

function toSceneRetention(w: z.infer<typeof WireSceneRetentionSchema>): SceneRetention {
  return {
    cohort: w.cohort,
    d1: w.d1,
    d7: w.d7,
    d30: w.d30,
  };
}

const WireSceneRetentionPointSchema = z.object({
  date: z.string(),
  cohort: z.number(),
  d1: z.number().nullable().default(null),
  d7: z.number().nullable().default(null),
  d30: z.number().nullable().default(null),
});

function toSceneRetentionPoint(w: z.infer<typeof WireSceneRetentionPointSchema>): SceneRetentionPoint {
  return {
    date: w.date,
    cohort: w.cohort,
    d1: w.d1,
    d7: w.d7,
    d30: w.d30,
  };
}

const WireSceneDailyStatsSchema = z.object({
  date: z.string(),
  visits: z.number().nullable().default(null),
  unique_users: z.number().nullable().default(null),
  new_users: z.number().nullable().default(null),
  median_active_time_s: z.number().nullable().default(null),
  peak_concurrent_users: z.number().nullable().default(null),
  messages_sent: z.number().nullable().default(null),
  emotes_played: z.number().nullable().default(null),
});

function toSceneDailyStats(w: z.infer<typeof WireSceneDailyStatsSchema>): SceneDailyStats {
  return {
    date: w.date,
    visits: w.visits,
    uniqueUsers: w.unique_users,
    newUsers: w.new_users,
    medianActiveTimeS: w.median_active_time_s,
    peakConcurrentUsers: w.peak_concurrent_users,
    messagesSent: w.messages_sent,
    emotesPlayed: w.emotes_played,
  };
}

const WireSceneStatsSchema = z.object({
  scene_type: WireSceneTypeSchema,
  scene_id: z.string(),
  title: z.string().nullable().default(null),
  deployer_address: z.string().nullable().default(null),
  windows: z.object({
      yesterday: WireSceneMetricsWindowSchema,
      last_7d: WireSceneMetricsWindowSchema,
      last_30d: WireSceneMetricsWindowSchema,
    }),
  retention: WireSceneRetentionSchema,
  retention_series: z.array(WireSceneRetentionPointSchema),
  daily: z.array(WireSceneDailyStatsSchema),
  deploy_dates: z.array(z.string()),
});

function toSceneStats(w: z.infer<typeof WireSceneStatsSchema>): SceneStats {
  return {
    sceneType: w.scene_type,
    sceneId: w.scene_id,
    title: w.title,
    deployerAddress: w.deployer_address,
    windows: {
        yesterday: toSceneMetricsWindow(w.windows.yesterday),
        last_7d: toSceneMetricsWindow(w.windows.last_7d),
        last_30d: toSceneMetricsWindow(w.windows.last_30d),
      },
    retention: toSceneRetention(w.retention),
    retentionSeries: w.retention_series.map((x) => toSceneRetentionPoint(x)),
    daily: w.daily.map((x) => toSceneDailyStats(x)),
    deployDates: w.deploy_dates,
  };
}

export const WireCreatorScenesStatsSchema = z.object({
  address: z.string(),
  as_of: z.string(),
  scenes: z.array(WireSceneStatsSchema),
});

function toCreatorScenesStats(w: z.infer<typeof WireCreatorScenesStatsSchema>): CreatorScenesStats {
  return {
    address: w.address,
    asOf: w.as_of,
    scenes: w.scenes.map((x) => toSceneStats(x)),
  };
}

export function parseCreatorScenesStats(
  raw: unknown,
): CreatorScenesStats {
  return toCreatorScenesStats(WireCreatorScenesStatsSchema.parse(raw));
}
