#!/usr/bin/env bash
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/_lib.sh"

PI_ENV="$ENV_DIR/catalyrst-profile-images.env"
CACHE_DIR="${PROFILE_IMAGES_CACHE_DIR:-$DATA_DIR/profile-images}"
RENDER_TMP="$CACHE_DIR/.render-tmp"
ORIGIN_URL="${PROFILE_IMAGES_ORIGIN_URL:?set PROFILE_IMAGES_ORIGIN_URL to this deployment own profile-images origin (no default -- the previous one was production)}"
CONTENT_URL="${PROFILE_IMAGES_CONTENT_URL:-http://127.0.0.1:5141/content}"
GODOT_PROJECT="${PROFILE_IMAGES_GODOT_PROJECT:-<CONTENT_ROOT>/godot-explorer}"
GODOT_BIN="${PROFILE_IMAGES_GODOT_BIN:-$GODOT_PROJECT/exports/decentraland.godot.client.x86_64}"
PORT="${PROFILE_IMAGES_PORT:-5152}"

log "creating cache dir $CACHE_DIR (+ render scratch $RENDER_TMP)"
mkdir -p "$CACHE_DIR" "$RENDER_TMP"

if [[ ! -x "$GODOT_BIN" ]]; then
  log "WARNING: godot client binary not found/executable at $GODOT_BIN"
  log "  build it with:  cd $GODOT_PROJECT && cargo run -- build -r && cargo run -- export --target linux"
  log "  the render backend will fail (502, or fall back to proxy if enabled) until it exists."
fi

if [[ -f "$PI_ENV" ]]; then
  log "reusing existing $PI_ENV (leaving as-is)"
else
  log "writing $PI_ENV"
  cat > "$PI_ENV" <<EOF
# auto-generated by scripts/bootstrap-catalyrst-profile-images.sh -- do not commit

HTTP_SERVER_HOST=127.0.0.1
HTTP_SERVER_PORT=$PORT

# Backend: "render" (local Godot avatar render on a throwaway X display -- PRIMARY),
# "proxy" (origin-pull) or "disabled".
PROFILE_IMAGES_BACKEND=render

# --- render backend ---
PROFILE_IMAGES_CONTENT_URL=$CONTENT_URL
PROFILE_IMAGES_GODOT_BIN=$GODOT_BIN
PROFILE_IMAGES_GODOT_PROJECT=$GODOT_PROJECT
PROFILE_IMAGES_RENDERING_METHOD=gl_compatibility
PROFILE_IMAGES_RENDERING_DRIVER=opengl3
PROFILE_IMAGES_GODOT_HEADLESS=false
PROFILE_IMAGES_RENDER_TIMEOUT_SECONDS=120
PROFILE_IMAGES_RENDER_MAX_CONCURRENT=1
PROFILE_IMAGES_RENDER_WORKDIR=$RENDER_TMP

# Explicit last-resort: fall back to the prod proxy when a render fails.
# Off by default -- keep the proxy out of the primary path.
PROFILE_IMAGES_RENDER_FALLBACK_PROXY=false
PROFILE_IMAGES_ORIGIN_URL=$ORIGIN_URL

# --- cache ---
PROFILE_IMAGES_CACHE_DIR=$CACHE_DIR
PROFILE_IMAGES_CACHE_TTL_SECONDS=86400

RUST_LOG=catalyrst_profile_images=info,tower_http=info
EOF
  chmod 600 "$PI_ENV"
fi

log "bootstrap-catalyrst-profile-images complete."
log "  next:  start the catalyrst-profile-images service using your process manager."
