
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addCheck: true
    addComment: false

tasks:
  - init: |
      npm i
      npm i -g @subsquid/cli
      docker compose pull
      gp sync-done setup
  - name: DB
    command: |
      gp sync-await setup
      sqd up
  - name: GraphQL API
    command: |
      gp sync-await setup
      sqd serve
  - command: |
      gp ports await 4350 
      gp preview $(gp url 4350)/graphql
  - name: Squid procesor
    command: |
      gp open src/processor.ts
      gp sync-await setup
      sqd build
      gp ports await 23798
      sqd process
