use std::io::Result;
use std::path::{Path, PathBuf};

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed=proto");
    let proto_files = [
        "proto/decentraland/sdk/development/local_development.proto",
        "proto/decentraland/kernel/comms/rfc5/ws_comms.proto",
    ];
    let mut config = prost_build::Config::new();
    config.compile_protos(&proto_files, &["proto"])?;
    generate_component_schema()?;
    generate_abgen_embed()?;
    generate_skills_embed()?;
    Ok(())
}

/// Embed every skill under skills/ — the vendored decentraland/sdk-skills set
/// plus our own — as the `EMBEDDED` table src/skills.rs includes. Walking the
/// directory here is what makes scripts/sync-sdk-skills.sh the whole update:
/// no file list is maintained by hand, and
/// `skills::tests::embedded_matches_the_source_tree` guards this walk against
/// a missing rerun-if-changed.
fn generate_skills_embed() -> Result<()> {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let root = manifest.join("skills");
    println!("cargo:rerun-if-changed={}", root.display());
    let mut names: Vec<String> = std::fs::read_dir(&root)?
        .flatten()
        .filter(|e| e.path().join("SKILL.md").is_file())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .collect();
    names.sort();
    let mut code = String::from(
        "// @generated by build.rs from skills/\npub const EMBEDDED: &[EmbeddedSkill] = &[\n",
    );
    for name in &names {
        let dir = root.join(name);
        let mut rels = Vec::new();
        collect_files(&dir, "", &mut rels)?;
        let mut rels: Vec<String> = rels
            .into_iter()
            .map(|r| r.trim_start_matches('/').to_string())
            .filter(|r| !r.split('/').any(|part| part.starts_with('.')))
            .filter(|r| r != "SKILL.md")
            .collect();
        rels.sort();
        rels.insert(0, "SKILL.md".to_string());
        code.push_str(&format!("    EmbeddedSkill {{ name: {name:?}, files: &[\n"));
        for rel in &rels {
            let abs = dir.join(rel);
            println!("cargo:rerun-if-changed={}", abs.display());
            if let Some(parent) = abs.parent() {
                println!("cargo:rerun-if-changed={}", parent.display());
            }
            code.push_str(&format!(
                "        ({rel:?}, include_str!({:?})),\n",
                abs.display().to_string()
            ));
        }
        code.push_str("    ] },\n");
    }
    code.push_str("];\n");
    std::fs::write(out_dir.join("skills_embedded.rs"), code)
}

/// Compile the vendored @dcl/protocol component protos into a static schema
/// table (messages, enums, component ids) that src/crdt_gen.rs uses to
/// serialize composite JSON into main.crdt without node or @dcl/inspector.
fn generate_component_schema() -> Result<()> {
    use prost::Message;

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let comp_dir = Path::new("proto/decentraland/sdk/components");
    let mut protos: Vec<PathBuf> = std::fs::read_dir(comp_dir)?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("proto"))
        .collect();
    protos.sort();

    let descriptor_path = out_dir.join("components_descriptor.bin");
    let gen_dir = out_dir.join("components-prost-gen");
    std::fs::create_dir_all(&gen_dir)?;
    let mut config = prost_build::Config::new();
    config.file_descriptor_set_path(&descriptor_path);
    config.out_dir(&gen_dir); // generated Rust types are unused; only the descriptor set matters
    config.compile_protos(&protos, &[PathBuf::from("proto")])?;

    let fds = prost_types::FileDescriptorSet::decode(&std::fs::read(&descriptor_path)?[..])
        .expect("decoding the component FileDescriptorSet");

    // First pass: assign stable indexes to every message and enum (nested included).
    let mut msg_index: Vec<(String, prost_types::DescriptorProto)> = Vec::new();
    let mut enum_index: Vec<(String, prost_types::EnumDescriptorProto)> = Vec::new();
    for file in &fds.file {
        let pkg = file.package();
        for m in &file.message_type {
            collect_messages(pkg, m, &mut msg_index, &mut enum_index);
        }
        for e in &file.enum_type {
            enum_index.push((format!("{pkg}.{}", e.name()), e.clone()));
        }
    }
    let msg_pos = |full: &str| msg_index.iter().position(|(n, _)| n == full);
    let enum_pos = |full: &str| enum_index.iter().position(|(n, _)| n == full);

    // Second pass: emit the static tables.
    let mut src =
        String::from("// @generated by build.rs from proto/decentraland/sdk/components\n");
    src.push_str("pub(crate) static MESSAGES: &[MsgDef] = &[\n");
    for (full, m) in &msg_index {
        let map_entry = m.options.as_ref().is_some_and(|o| o.map_entry());
        let mut fields: Vec<&prost_types::FieldDescriptorProto> = m.field.iter().collect();
        fields.sort_by_key(|f| f.number());
        src.push_str(&format!(
            "    MsgDef {{ name: {full:?}, map_entry: {map_entry}, fields: &[\n"
        ));
        for f in fields {
            use prost_types::field_descriptor_proto::{Label, Type};
            let repeated = f.label() == Label::Repeated;
            let optional = f.proto3_optional();
            let strip = |s: &str| s.trim_start_matches('.').to_string();
            let kind = match f.r#type() {
                Type::Double => "FieldKind::Double".into(),
                Type::Float => "FieldKind::Float".into(),
                Type::Int32 => "FieldKind::Int32".into(),
                Type::Int64 => "FieldKind::Int64".into(),
                Type::Uint32 => "FieldKind::Uint32".into(),
                Type::Uint64 => "FieldKind::Uint64".into(),
                Type::Sint32 => "FieldKind::Sint32".into(),
                Type::Sint64 => "FieldKind::Sint64".into(),
                Type::Fixed32 => "FieldKind::Fixed32".into(),
                Type::Fixed64 => "FieldKind::Fixed64".into(),
                Type::Sfixed32 => "FieldKind::Sfixed32".into(),
                Type::Sfixed64 => "FieldKind::Sfixed64".into(),
                Type::Bool => "FieldKind::Bool".into(),
                Type::String => "FieldKind::Str".into(),
                Type::Bytes => "FieldKind::Bytes".into(),
                Type::Enum => {
                    let full = strip(f.type_name());
                    let idx = enum_pos(&full)
                        .unwrap_or_else(|| panic!("enum {full} not found in descriptor set"));
                    format!("FieldKind::Enum({idx})")
                }
                Type::Message | Type::Group => {
                    let full = strip(f.type_name());
                    let idx = msg_pos(&full)
                        .unwrap_or_else(|| panic!("message {full} not found in descriptor set"));
                    format!("FieldKind::Msg({idx})")
                }
            };
            // proto3 packs numeric repeated fields unless packed=false is explicit
            let packable = !matches!(
                f.r#type(),
                Type::String | Type::Bytes | Type::Message | Type::Group
            );
            let packed =
                repeated && packable && f.options.as_ref().and_then(|o| o.packed) != Some(false);
            // proto3 optional is implemented as a synthetic oneof; only real
            // oneofs get the ts-proto {$case} JSON shape
            let oneof = match f.oneof_index {
                Some(i) if !optional => {
                    let name = m.oneof_decl[i as usize].name();
                    format!("Some({:?})", camel_case(name))
                }
                _ => "None".to_string(),
            };
            src.push_str(&format!(
                "        FieldDef {{ number: {}, json_name: {:?}, kind: {kind}, repeated: {repeated}, packed: {packed}, optional: {optional}, oneof: {oneof} }},\n",
                f.number(),
                f.json_name(),
            ));
        }
        src.push_str("    ] },\n");
    }
    src.push_str("];\n");

    src.push_str("pub(crate) static ENUMS: &[EnumDef] = &[\n");
    for (full, e) in &enum_index {
        let values: Vec<String> = e
            .value
            .iter()
            .map(|v| format!("({:?}, {})", v.name(), v.number()))
            .collect();
        src.push_str(&format!(
            "    EnumDef {{ name: {full:?}, values: &[{}] }},\n",
            values.join(", ")
        ));
    }
    src.push_str("];\n");

    src.push_str("pub(crate) static COMPONENTS: &[ComponentDef] = &[\n");
    for proto in &protos {
        let text = std::fs::read_to_string(proto)?;
        let Some(id) = parse_ecs_component_id(&text) else {
            println!(
                "cargo:warning=no ecs_component_id in {}; skipping",
                proto.display()
            );
            continue;
        };
        let stem = proto.file_stem().unwrap().to_string_lossy();
        let pascal = pascal_case(&stem);
        let full = format!("decentraland.sdk.components.PB{pascal}");
        let Some(idx) = msg_pos(&full) else {
            println!("cargo:warning=message {full} not found; skipping component");
            continue;
        };
        src.push_str(&format!(
            "    ComponentDef {{ name: \"core::{pascal}\", id: {id}, msg: {idx} }},\n"
        ));
    }
    src.push_str("];\n");

    std::fs::write(out_dir.join("components_schema.rs"), src)
}

fn collect_messages(
    prefix: &str,
    m: &prost_types::DescriptorProto,
    msgs: &mut Vec<(String, prost_types::DescriptorProto)>,
    enums: &mut Vec<(String, prost_types::EnumDescriptorProto)>,
) {
    let full = format!("{prefix}.{}", m.name());
    msgs.push((full.clone(), m.clone()));
    for e in &m.enum_type {
        enums.push((format!("{full}.{}", e.name()), e.clone()));
    }
    for nested in &m.nested_type {
        collect_messages(&full, nested, msgs, enums);
    }
}

fn parse_ecs_component_id(proto_text: &str) -> Option<u32> {
    let idx = proto_text.find("ecs_component_id")?;
    let rest = &proto_text[idx..];
    let eq = rest.find('=')?;
    let digits: String = rest[eq + 1..]
        .trim_start()
        .chars()
        .take_while(|c| c.is_ascii_digit())
        .collect();
    digits.parse().ok()
}

fn pascal_case(snake: &str) -> String {
    snake
        .split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn camel_case(snake: &str) -> String {
    let pascal = pascal_case(snake);
    let mut c = pascal.chars();
    match c.next() {
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

/// Embed the abgen sidecar. Unconditional: every dcl-one-sdk binary carries a
/// working asset-bundle server, so `start` never has to tell a user to go
/// install one. The bytes come from the release pinned in abgen-release.lock
/// (downloaded into a shared cache and sha256-verified) unless ABGEN_EMBED_BIN
/// names a different abgen — the escape hatch for offline builds, nix, and
/// anyone testing an abgen they built themselves.
///
/// Files are stored deflate-compressed: the macOS arm64 abgen is 36 MB on disk
/// and 13 MB compressed, and paying a few ms of inflate on first `start` beats
/// putting the difference in every binary.
fn generate_abgen_embed() -> Result<()> {
    println!("cargo:rerun-if-env-changed=ABGEN_EMBED_BIN");
    println!("cargo:rerun-if-env-changed=ABGEN_EMBED_CACHE");
    println!("cargo:rerun-if-changed=abgen-release.lock");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("abgen_embed_data.rs");

    let (bin_path, version) = match std::env::var("ABGEN_EMBED_BIN").unwrap_or_default() {
        v if v.is_empty() => {
            let lock = AbgenLock::read()?;
            (fetch_pinned_abgen(&lock)?, lock.version)
        }
        v => {
            let p = PathBuf::from(&v);
            if !p.is_file() {
                panic!("ABGEN_EMBED_BIN={v} is not a file; it must point at an abgen executable");
            }
            (p, "custom".to_string())
        }
    };
    let bin_name = bin_path
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .expect("ABGEN_EMBED_BIN has no file name");
    let dir = bin_path.parent().map(Path::to_path_buf).unwrap_or_default();

    // A release abgen is one self-contained executable. A source build may sit
    // beside template/ and shader/ (its ABGEN_ROOT layout) and, on windows,
    // loose DLLs; carry those along when they happen to be there.
    let mut rels = vec![bin_name.clone()];
    for sub in ["template", "shader", "bin", "lib"] {
        collect_files(&dir.join(sub), sub, &mut rels)?;
    }
    for entry in std::fs::read_dir(&dir)?.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.ends_with(".dll") && entry.path().is_file() {
            rels.push(name);
        }
    }
    rels.sort();
    rels.dedup();

    let blob_dir = out_dir.join("abgen-embed");
    std::fs::create_dir_all(&blob_dir)?;
    let mut hash: u64 = 0xcbf29ce484222325;
    let mut code = String::from(
        "/// (path relative to the extraction root, deflate stream, uncompressed length)\npub static FILES: &[(&str, &[u8], usize)] = &[\n",
    );
    for (i, rel) in rels.iter().enumerate() {
        let abs = dir.join(rel);
        println!("cargo:rerun-if-changed={}", abs.display());
        let raw = std::fs::read(&abs)?;
        fnv1a64(&mut hash, rel.as_bytes());
        fnv1a64(&mut hash, &raw);
        let blob = blob_dir.join(format!("{i}.z"));
        std::fs::write(&blob, deflate(&raw))?;
        code.push_str(&format!(
            "    ({rel:?}, include_bytes!({:?}), {}),\n",
            blob.display().to_string(),
            raw.len()
        ));
    }
    code.push_str("];\n");
    code.push_str(&format!("pub const BIN_NAME: &str = {bin_name:?};\n"));
    code.push_str(&format!("pub const VERSION: &str = {version:?};\n"));
    code.push_str(&format!("pub const TAG: &str = \"{hash:016x}\";\n"));
    std::fs::write(&dest, code)
}

fn deflate(raw: &[u8]) -> Vec<u8> {
    use std::io::Write;
    let mut e = flate2::write::DeflateEncoder::new(Vec::new(), flate2::Compression::best());
    e.write_all(raw).expect("deflate");
    e.finish().expect("deflate")
}

fn collect_files(dir: &Path, prefix: &str, out: &mut Vec<String>) -> Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in std::fs::read_dir(dir)?.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        let rel = format!("{prefix}/{name}");
        if entry.path().is_dir() {
            collect_files(&entry.path(), &rel, out)?;
        } else if entry.path().is_file() {
            out.push(rel);
        }
    }
    Ok(())
}

struct AbgenLock {
    version: String,
    url: String,
    /// abgen release target -> sha256 of its archive
    targets: std::collections::BTreeMap<String, String>,
}

impl AbgenLock {
    fn read() -> Result<Self> {
        let text = std::fs::read_to_string("abgen-release.lock")?;
        let mut version = String::new();
        let mut url = String::new();
        let mut targets = std::collections::BTreeMap::new();
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((k, v)) = line.split_once('=') else {
                continue;
            };
            let (k, v) = (k.trim().to_string(), v.trim().to_string());
            match k.as_str() {
                "version" => version = v,
                "url" => url = v,
                _ => {
                    targets.insert(k, v);
                }
            }
        }
        assert!(
            !version.is_empty() && !url.is_empty() && !targets.is_empty(),
            "abgen-release.lock is missing version, url or target hashes"
        );
        Ok(AbgenLock {
            version,
            url,
            targets,
        })
    }

    /// The abgen release target for the crate's build target. abgen ships a
    /// standalone executable, so *-msvc maps to the -gnu archive: nothing links
    /// against it.
    fn release_target(&self) -> String {
        let os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
        let arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
        match (os.as_str(), arch.as_str()) {
            ("macos", "aarch64") => "aarch64-apple-darwin",
            ("macos", "x86_64") => "x86_64-apple-darwin",
            ("linux", "aarch64") => "aarch64-unknown-linux-gnu",
            ("linux", "x86_64") => "x86_64-unknown-linux-gnu",
            ("windows", "aarch64") => "aarch64-pc-windows-gnullvm",
            ("windows", "x86_64") => "x86_64-pc-windows-gnu",
            _ => panic!(
                "abgen publishes no release for {os}/{arch}; build an abgen for it and point ABGEN_EMBED_BIN at the executable"
            ),
        }
        .to_string()
    }
}

/// Download (once, into a shared cache) and unpack the pinned abgen release for
/// this build target, returning the path to its executable.
fn fetch_pinned_abgen(lock: &AbgenLock) -> Result<PathBuf> {
    let target = lock.release_target();
    let sha = lock.targets.get(&target).unwrap_or_else(|| {
        panic!("abgen-release.lock has no sha256 for target {target}");
    });
    let cache = abgen_cache_dir().join(&lock.version).join(&target);
    let exe = if target.contains("windows") {
        "abgen.exe"
    } else {
        "abgen"
    };
    let unpacked = cache.join("dist").join(exe);
    if unpacked.is_file() {
        return Ok(unpacked);
    }
    std::fs::create_dir_all(&cache)?;

    let url = lock
        .url
        .replace("{version}", &lock.version)
        .replace("{target}", &target);
    let archive = cache.join(format!("archive.tar.gz.{}", std::process::id()));
    // cargo replays a build script's warnings on cached runs, so word this as
    // what happened once, not as what is happening now.
    println!(
        "cargo:warning=downloaded pinned abgen {} for {target} into {}",
        lock.version,
        cache.display()
    );
    let status = std::process::Command::new("curl")
        .args(["-fsSL", "--retry", "3", "--retry-delay", "2", "-o"])
        .arg(&archive)
        .arg(&url)
        .status();
    match status {
        Ok(s) if s.success() => {}
        other => {
            let _ = std::fs::remove_file(&archive);
            panic!(
                "could not download the pinned abgen from {url} ({other:?}).\n\
                 dcl-one-sdk always embeds abgen; to build without network access, unpack that \
                 archive yourself and set ABGEN_EMBED_BIN=<dir>/{exe}"
            );
        }
    }

    let got = sha256_hex(&std::fs::read(&archive)?);
    if &got != sha {
        let _ = std::fs::remove_file(&archive);
        panic!("{url} hashed to {got}, but abgen-release.lock pins {sha}");
    }

    // Unpack into a private staging dir, then publish the executable with a
    // rename so two concurrent cargo builds cannot see a half-written binary.
    let stage = cache.join(format!("stage.{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&stage);
    std::fs::create_dir_all(&stage)?;
    let status = std::process::Command::new("tar")
        .arg("-xzf")
        .arg(&archive)
        .arg("-C")
        .arg(&stage)
        .status()?;
    assert!(
        status.success(),
        "tar failed to unpack {}",
        archive.display()
    );
    let mut found = Vec::new();
    collect_files(&stage, "", &mut found)?;
    let rel = found
        .iter()
        .find(|r| r.rsplit('/').next() == Some(exe))
        .unwrap_or_else(|| panic!("no {exe} inside {url}"));
    let staged = stage.join(rel.trim_start_matches('/'));
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&staged, std::fs::Permissions::from_mode(0o755))?;
    }
    // The linux archives are launcher bundles (abgen + bin/abgen.bin + a
    // bundled lib/ loader), so publish the executable's whole directory; a
    // rename losing to a concurrent build is fine as long as the winner's
    // dist is in place.
    let dist_src = staged
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| stage.clone());
    if std::fs::rename(&dist_src, cache.join("dist")).is_err() && !unpacked.is_file() {
        panic!(
            "could not publish the unpacked abgen into {}",
            cache.display()
        );
    }
    let _ = std::fs::remove_dir_all(&stage);
    let _ = std::fs::remove_file(&archive);
    Ok(unpacked)
}

/// Shared across every checkout and target dir on the machine — a 13 MB
/// download per abgen release, not per `cargo clean`.
fn abgen_cache_dir() -> PathBuf {
    if let Ok(v) = std::env::var("ABGEN_EMBED_CACHE") {
        if !v.is_empty() {
            return PathBuf::from(v);
        }
    }
    if let Ok(v) = std::env::var("CARGO_HOME") {
        if !v.is_empty() {
            return PathBuf::from(v).join("dcl-one-sdk-abgen");
        }
    }
    let home = std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .unwrap_or_else(|_| ".".to_string());
    PathBuf::from(home).join(".cache").join("dcl-one-sdk-abgen")
}

fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::Digest;
    let mut h = sha2::Sha256::new();
    h.update(bytes);
    h.finalize().iter().map(|b| format!("{b:02x}")).collect()
}

fn fnv1a64(hash: &mut u64, bytes: &[u8]) {
    for &b in bytes {
        *hash ^= b as u64;
        *hash = hash.wrapping_mul(0x100000001b3);
    }
}
