pub mod auth_chain;
pub mod eip1654;
pub mod error;
pub mod metadata_gate;
pub mod recover;
pub mod rpc_validator;
pub mod sign;
pub mod signed_fetch;
pub mod signer;
pub mod validation_cache;
pub mod verify;

pub use auth_chain::{AuthChain, AuthLink, AuthLinkType};
pub use eip1654::{verify_eip1654, Eip1654Validator};
pub use error::AuthError;
pub use metadata_gate::{reject_if_signer, SignerGate, SignerGateError};
pub use rpc_validator::RpcEip1654Validator;
pub use sign::{create_simple_auth_chain, SignError, Wallet};
pub use signed_fetch::default_eip1654_validator;
pub use signer::Signer;
pub use validation_cache::ValidationCache;
