use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(
    feature = "ts",
    derive(ts_rs::TS),
    ts(export, export_to = "validator/")
)]
#[serde(rename_all = "camelCase")]
pub enum LandRightLeg {
    Owner,
    Operator,
    UpdateOperator,
    UpdateManager,
    ApprovedForAll,
}

pub const DEPLOY_GRANTING_LEGS: [LandRightLeg; 5] = [
    LandRightLeg::Owner,
    LandRightLeg::Operator,
    LandRightLeg::UpdateOperator,
    LandRightLeg::UpdateManager,
    LandRightLeg::ApprovedForAll,
];

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(
    feature = "ts",
    derive(ts_rs::TS),
    ts(export, export_to = "validator/")
)]
#[serde(rename_all = "camelCase")]
pub struct ParcelPermissionFlags {
    pub owner: bool,
    pub operator: bool,
    pub update_operator: bool,
    pub update_manager: bool,
    pub approved_for_all: bool,
}

impl ParcelPermissionFlags {
    pub fn leg(&self, leg: LandRightLeg) -> bool {
        match leg {
            LandRightLeg::Owner => self.owner,
            LandRightLeg::Operator => self.operator,
            LandRightLeg::UpdateOperator => self.update_operator,
            LandRightLeg::UpdateManager => self.update_manager,
            LandRightLeg::ApprovedForAll => self.approved_for_all,
        }
    }

    pub fn grants_deploy(&self) -> bool {
        DEPLOY_GRANTING_LEGS.iter().any(|&leg| self.leg(leg))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_flags_denies() {
        assert!(!ParcelPermissionFlags::default().grants_deploy());
    }

    #[test]
    fn each_granting_leg_grants_alone() {
        for &leg in &DEPLOY_GRANTING_LEGS {
            let mut flags = ParcelPermissionFlags::default();
            match leg {
                LandRightLeg::Owner => flags.owner = true,
                LandRightLeg::Operator => flags.operator = true,
                LandRightLeg::UpdateOperator => flags.update_operator = true,
                LandRightLeg::UpdateManager => flags.update_manager = true,
                LandRightLeg::ApprovedForAll => flags.approved_for_all = true,
            }
            assert!(flags.grants_deploy(), "{leg:?} should grant deploy");
        }
    }

    #[test]
    fn serialized_shape_matches_lambdas_permissions_response() {
        let json = serde_json::to_string(&ParcelPermissionFlags::default()).unwrap();
        assert_eq!(
            json,
            "{\"owner\":false,\"operator\":false,\"updateOperator\":false,\"updateManager\":false,\"approvedForAll\":false}"
        );
    }

    #[test]
    fn legs_serialize_to_flag_keys() {
        for &leg in &DEPLOY_GRANTING_LEGS {
            let key = serde_json::to_value(leg).unwrap();
            let flags = serde_json::to_value(ParcelPermissionFlags::default()).unwrap();
            assert!(flags
                .as_object()
                .unwrap()
                .contains_key(key.as_str().unwrap()));
        }
    }

    #[cfg(feature = "ts")]
    #[test]
    fn export_bindings_deploy_granting_legs() {
        let base = std::env::var("TS_RS_EXPORT_DIR").unwrap_or_else(|_| "./bindings".to_string());
        let dir = std::path::Path::new(&base).join("validator");
        std::fs::create_dir_all(&dir).unwrap();
        let legs: Vec<String> = DEPLOY_GRANTING_LEGS
            .iter()
            .map(|leg| {
                format!(
                    "\"{}\"",
                    serde_json::to_value(leg).unwrap().as_str().unwrap()
                )
            })
            .collect();
        assert!(
            !legs.is_empty(),
            "DEPLOY_GRANTING_LEGS is empty: the exported predicate would grant nothing"
        );
        let body = format!(
            "// This file was generated by catalyrst-validator's export_bindings_deploy_granting_legs test. Do not edit this file manually.\nimport type {{ LandRightLeg }} from \"./LandRightLeg\";\n\nexport const DEPLOY_GRANTING_LEGS = [{}] as const satisfies readonly LandRightLeg[];\n",
            legs.join(", ")
        );
        std::fs::write(dir.join("deployGrantingLegs.ts"), body).unwrap();
    }
}
