use serde::{Deserialize, Serialize};

use crate::error::ValidationResponse;
use crate::types::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MerkleProof {
    pub proof: Vec<String>,
    pub index: u64,
    pub entity_hash: String,
    pub hashing_keys: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThirdPartyProps {
    pub merkle_proof: MerkleProof,
    #[serde(default)]
    pub content: std::collections::HashMap<String, String>,
    pub id: String,
}

/// Hashing keys a third-party wearable's merkle proof must commit for the checks to be trustworthy.
pub const WEARABLE_REQUIRED_HASHING_KEYS: &[&str] = &["id", "content", "data"];

/// Hashing keys a third-party emote's merkle proof must commit for the checks to be trustworthy.
pub const EMOTE_REQUIRED_HASHING_KEYS: &[&str] = &["id", "content", "emoteDataADR74"];

pub fn validate_third_party_merkle_proof_content(
    deployment: &DeploymentToValidate,
    required_hashing_keys: &[&str],
    item_label: &str,
) -> ValidationResponse {
    let entity = &deployment.entity;
    let metadata = match &entity.metadata {
        Some(m) => m,
        None => return ValidationResponse::Ok,
    };

    if metadata.get("merkleProof").is_none() {
        return ValidationResponse::Ok;
    }

    let tp_props: ThirdPartyProps = match serde_json::from_value(metadata.clone()) {
        Ok(p) => p,
        Err(e) => {
            return ValidationResponse::fail(format!("Failed to parse third-party metadata: {e}"));
        }
    };

    if entity.pointers.is_empty() || tp_props.id.to_lowercase() != entity.pointers[0].to_lowercase()
    {
        return ValidationResponse::fail(format!(
            "The id '{}' does not match the pointer '{}'",
            tp_props.id,
            entity.pointers.first().map(|s| s.as_str()).unwrap_or("")
        ));
    }

    if let Some(missing_key) = required_hashing_keys
        .iter()
        .find(|key| !tp_props.merkle_proof.hashing_keys.iter().any(|k| k == *key))
    {
        return ValidationResponse::fail(format!(
            "The third-party {item_label} merkle proof must commit the '{missing_key}' field"
        ));
    }

    let all_content_in_files = tp_props.content.iter().all(|(file, hash)| {
        entity
            .content
            .iter()
            .any(|c| c.file == *file && c.hash == *hash)
    });

    let all_files_in_content = entity.content.iter().all(|c| {
        tp_props
            .content
            .get(&c.file)
            .map(|h| h == &c.hash)
            .unwrap_or(false)
    });

    if !all_content_in_files || !all_files_in_content {
        return ValidationResponse::fail(
            "The content declared in the metadata does not match the files uploaded with the entity"
                .to_string(),
        );
    }

    if tp_props.merkle_proof.entity_hash.is_empty() {
        return ValidationResponse::fail(
            "The entity hash in the merkle proof is empty".to_string(),
        );
    }

    let generated = keccak256_hash(metadata, &tp_props.merkle_proof.hashing_keys);
    if !tp_props
        .merkle_proof
        .entity_hash
        .trim_start_matches("0x")
        .eq_ignore_ascii_case(&generated)
    {
        return ValidationResponse::fail(
            "The hash provided in the merkleProof doesn't match the one generated by the validator"
                .to_string(),
        );
    }

    if tp_props.merkle_proof.proof.is_empty() {
        return ValidationResponse::fail("The merkle proof is empty".to_string());
    }

    if tp_props.merkle_proof.hashing_keys.is_empty() {
        return ValidationResponse::fail(
            "The hashing keys in the merkle proof are empty".to_string(),
        );
    }

    ValidationResponse::Ok
}

pub fn verify_third_party_merkle_proof(proof: &MerkleProof, root: &[u8; 32]) -> bool {
    let decoded: Option<Vec<[u8; 32]>> = proof
        .proof
        .iter()
        .map(|p| crate::merkle::decode_hash32(p))
        .collect();
    let Some(decoded) = decoded else {
        return false;
    };
    crate::merkle::verify_proof(proof.index, &proof.entity_hash, &decoded, root)
}

fn keccak256_hash(metadata: &serde_json::Value, keys: &[String]) -> String {
    let mut s = String::from("{");
    let mut first = true;
    for k in keys {
        if let Some(v) = metadata.get(k) {
            if !first {
                s.push(',');
            }
            first = false;
            s.push_str(&serde_json::to_string(k).unwrap());
            s.push(':');
            s.push_str(&serde_json::to_string(v).unwrap());
        }
    }
    s.push('}');
    hex::encode(alloy_primitives::keccak256(s.as_bytes()))
}

pub fn get_third_party_id(urn: &str) -> Option<String> {
    let parts: Vec<&str> = urn.split(':').collect();
    if parts.len() >= 5 && parts[3].starts_with("collections-thirdparty") {
        Some(parts[..5].join(":"))
    } else {
        None
    }
}

pub fn hex_to_bytes(value: &str) -> Option<Vec<u8>> {
    catalyrst_types::decode_hex_0x(value).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn third_party_id_extraction() {
        assert_eq!(
            get_third_party_id(
                "urn:decentraland:matic:collections-thirdparty:tp-name:collection:item"
            ),
            Some("urn:decentraland:matic:collections-thirdparty:tp-name".to_string())
        );
        assert_eq!(
            get_third_party_id("urn:decentraland:matic:collections-v2:0xabc:0"),
            None
        );
    }

    #[test]
    fn hex_conversion() {
        assert_eq!(
            hex_to_bytes("0xdeadbeef"),
            Some(vec![0xde, 0xad, 0xbe, 0xef])
        );
        assert_eq!(hex_to_bytes("deadbeef"), Some(vec![0xde, 0xad, 0xbe, 0xef]));
        assert_eq!(hex_to_bytes("0x"), Some(vec![]));
    }

    #[test]
    fn keccak256_hash_matches_picked_order() {
        let metadata = serde_json::json!({
            "id": "urn:tp",
            "name": "Item",
            "description": "desc",
            "extra": "ignored"
        });
        let keys = vec!["name".to_string(), "description".to_string()];
        let expected = hex::encode(alloy_primitives::keccak256(
            br#"{"name":"Item","description":"desc"}"#,
        ));
        assert_eq!(keccak256_hash(&metadata, &keys), expected);
    }

    #[test]
    fn validate_non_third_party_passes() {
        let deployment = DeploymentToValidate {
            entity: Entity {
                id: "bafkrei".to_string(),
                entity_type: EntityType::Wearable,
                pointers: vec!["urn:decentraland:matic:collections-v2:0xabc:0".to_string()],
                timestamp: 1700000000000,
                content: vec![],
                version: "v3".to_string(),
                metadata: Some(serde_json::json!({
                    "name": "Regular Wearable",
                    "data": { "representations": [], "tags": [], "category": "hat" }
                })),
            },
            files: std::collections::HashMap::new(),
            audit_info: DeploymentAuditInfo { auth_chain: vec![] },
        };

        assert!(validate_third_party_merkle_proof_content(
            &deployment,
            WEARABLE_REQUIRED_HASHING_KEYS,
            "wearable"
        )
        .is_ok());
    }

    fn third_party_deployment(pointer: &str, hashing_keys: &[&str]) -> DeploymentToValidate {
        let keys: Vec<String> = hashing_keys.iter().map(|k| k.to_string()).collect();
        let mut metadata = serde_json::json!({
            "id": pointer,
            "name": "TP Item",
            "description": "third-party item",
            "content": {},
            "data": { "representations": [], "tags": [], "category": "hat" },
            "emoteDataADR74": { "representations": [], "tags": [], "category": "dance" },
        });
        let entity_hash = keccak256_hash(&metadata, &keys);
        metadata["merkleProof"] = serde_json::json!({
            "proof": ["0x0000000000000000000000000000000000000000000000000000000000000001"],
            "index": 0,
            "entityHash": entity_hash,
            "hashingKeys": keys,
        });

        DeploymentToValidate {
            entity: Entity {
                id: "bafkrei".to_string(),
                entity_type: EntityType::Wearable,
                pointers: vec![pointer.to_string()],
                timestamp: 1700000000000,
                content: vec![],
                version: "v3".to_string(),
                metadata: Some(metadata),
            },
            files: std::collections::HashMap::new(),
            audit_info: DeploymentAuditInfo { auth_chain: vec![] },
        }
    }

    const TP_POINTER: &str =
        "urn:decentraland:matic:collections-thirdparty:tp-name:collection:item";

    #[test]
    fn wearable_proof_committing_required_keys_passes() {
        let deployment = third_party_deployment(
            TP_POINTER,
            &["id", "content", "data", "name", "description"],
        );
        assert!(validate_third_party_merkle_proof_content(
            &deployment,
            WEARABLE_REQUIRED_HASHING_KEYS,
            "wearable"
        )
        .is_ok());
    }

    #[test]
    fn wearable_proof_missing_content_key_fails() {
        let deployment = third_party_deployment(TP_POINTER, &["id", "data"]);
        let result = validate_third_party_merkle_proof_content(
            &deployment,
            WEARABLE_REQUIRED_HASHING_KEYS,
            "wearable",
        );
        let errors = result.errors().expect("must fail");
        assert_eq!(
            errors[0],
            "The third-party wearable merkle proof must commit the 'content' field"
        );
    }

    #[test]
    fn wearable_leaf_reused_as_emote_fails() {
        let deployment = third_party_deployment(TP_POINTER, &["id", "content", "data"]);
        assert!(validate_third_party_merkle_proof_content(
            &deployment,
            WEARABLE_REQUIRED_HASHING_KEYS,
            "wearable"
        )
        .is_ok());

        let result = validate_third_party_merkle_proof_content(
            &deployment,
            EMOTE_REQUIRED_HASHING_KEYS,
            "emote",
        );
        let errors = result.errors().expect("must fail as emote");
        assert_eq!(
            errors[0],
            "The third-party emote merkle proof must commit the 'emoteDataADR74' field"
        );
    }

    #[test]
    fn emote_proof_committing_required_keys_passes() {
        let deployment = third_party_deployment(TP_POINTER, &["id", "content", "emoteDataADR74"]);
        assert!(validate_third_party_merkle_proof_content(
            &deployment,
            EMOTE_REQUIRED_HASHING_KEYS,
            "emote"
        )
        .is_ok());
    }

    #[test]
    fn proof_missing_id_key_fails() {
        let deployment = third_party_deployment(TP_POINTER, &["content", "data"]);
        let result = validate_third_party_merkle_proof_content(
            &deployment,
            WEARABLE_REQUIRED_HASHING_KEYS,
            "wearable",
        );
        let errors = result.errors().expect("must fail");
        assert_eq!(
            errors[0],
            "The third-party wearable merkle proof must commit the 'id' field"
        );
    }
}
