# The canonical service-topology facts. Pure data -- no functions, no store
# paths, no pkgs/lib -- so every consumer can `nix eval --json --file` it:
#   1. this NixOS module (units read their ports/credentials from here),
#   2. the compose/self-host generator and the /server operator page
#      (catalyrst/sites .../operator/registry.ts drift-gates against it),
#   3. private per-instance registries (deploy/ports.nix, NOT exported)
#      assert their service keys against this attrset -- instance-specific
#      port allocations live with the instance, identity lives here.
#
#   units    -- the module's process topology: one row per systemd unit the
#              module can run; the compose fleet maps 1:1 onto the
#              long-running rows. `port` is the module's default listener
#              (null = no listener). `subService` names the gate flag under
#              services.catalyrst.subServices (a dotted path means a gate
#              outside subServices; null = runs whenever the module is on).
#   services -- the logical product surfaces: each points at the unit that
#              carries it in the module (`unit`/`bundle`; bundle "core" =
#              rides catalyrst-sync, "standalone" = its own process).
#   env      -- operator-supplied variables in the service's secret env file;
#              autoGenerated = true means a module oneshot mints it (wizards
#              must not prompt for those). In-store unit environment is not
#              repeated here -- the module files are its source.
{
  units = {
    catalyrst-sync = {
      bin = "catalyrst-live";
      pkg = "catalyrst";
      port = 5141;
      extraPorts = [ ];
      subService = null;
      kind = "long-running";
      credFiles = [ "catalyrst-admin.env" ];
      healthPath = "/about";
      healthExpect = "2xx";
    };
    catalyrst-explore = {
      bin = "catalyrst-explore";
      pkg = "catalyrst-all";
      port = 5143;
      extraPorts = [ ];
      subService = "explore";
      kind = "long-running";
      credFiles = [ "livekit-api.env" ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-create = {
      bin = "catalyrst-create";
      pkg = "catalyrst-all";
      port = 5144;
      extraPorts = [ ];
      subService = "create";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-social = {
      bin = "catalyrst-social";
      pkg = "catalyrst-all";
      port = 5145;
      extraPorts = [ ];
      subService = "social";
      kind = "long-running";
      credFiles = [ "livekit-api.env" ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-data = {
      bin = "catalyrst-data";
      pkg = "catalyrst-all";
      port = 5146;
      extraPorts = [ ];
      subService = "data";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-ab-cdn = {
      bin = "abgen";
      pkg = "abgen";
      port = 5147;
      extraPorts = [ ];
      subService = "abCdn";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-social-rpc = {
      bin = "catalyrst-social-rpc";
      pkg = "catalyrst-all";
      port = 5148;
      extraPorts = [ ];
      subService = "socialRpc";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-explorer-api = {
      bin = "catalyrst-explorer-api";
      pkg = "catalyrst-all";
      port = 5137;
      extraPorts = [ ];
      subService = "explorerApi";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-telemetry = {
      bin = "catalyrst-telemetry";
      pkg = "catalyrst-all";
      port = 5150;
      extraPorts = [ ];
      subService = "telemetry";
      kind = "long-running";
      credFiles = [ "telemetry-admin-token" ];
      healthPath = "/healthz";
      healthExpect = "2xx";
    };
    catalyrst-world-storage = {
      bin = "catalyrst-world-storage";
      pkg = "catalyrst-all";
      port = 5154;
      extraPorts = [ ];
      subService = "worldStorage";
      kind = "long-running";
      credFiles = [ "catalyrst-world-storage.env" ];
      healthPath = "/ping";
      healthExpect = "2xx";
    };
    catalyrst-profile-images = {
      bin = "catalyrst-profile-images";
      pkg = "catalyrst-all";
      port = 5161;
      extraPorts = [ ];
      subService = "profileImages";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-signatures = {
      bin = "catalyrst-signatures";
      pkg = "catalyrst-all";
      port = 5159;
      extraPorts = [ ];
      subService = "signatures";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-governance = {
      bin = "catalyrst-governance";
      pkg = "catalyrst-governance";
      port = 5151;
      extraPorts = [ ];
      subService = "governance";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-presence = {
      bin = "catalyrst-presence";
      pkg = "catalyrst-presence";
      port = 5152;
      extraPorts = [ ];
      subService = "presence";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-opensea-resolver = {
      bin = "opensea-resolver.mjs";
      pkg = null;
      port = 5162;
      extraPorts = [ ];
      subService = "gateway.enable";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
    };
    catalyrst-scene-state = {
      bin = "catalyrst-scene-state";
      pkg = "catalyrst-scene-state";
      port = 5209;
      extraPorts = [ ];
      subService = "sceneState";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/ping";
      healthExpect = "2xx";
    };
    catalyrst-sites = {
      bin = "sites-server";
      pkg = "sites";
      port = 5158;
      extraPorts = [ ];
      subService = "sites";
      kind = "long-running";
      credFiles = [
        "sites.env"
        "operator.env"
      ];
      healthPath = "/";
      healthExpect = "2xx";
    };
    nats = {
      bin = "nats-server";
      pkg = "nixpkgs.nats-server";
      port = 4222;
      extraPorts = [ 8222 ];
      subService = "comms";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/varz";
      healthExpect = "any-http";
    };
    libretranslate = {
      bin = "libretranslate";
      pkg = "nixpkgs.libretranslate";
      port = 5164;
      extraPorts = [ ];
      subService = "social";
      kind = "long-running";
      credFiles = [ ];
      healthPath = "/languages";
      healthExpect = "2xx";
    };
    livekit = {
      bin = "livekit-server";
      pkg = "nixpkgs.livekit";
      port = 7880;
      extraPorts = [
        7881
        7882
      ];
      subService = "comms";
      kind = "long-running";
      credFiles = [ "livekit.yaml" ];
      healthPath = "/";
      healthExpect = "any-http";
    };
    catalyrst-archipelago = {
      bin = "catalyrst-archipelago";
      pkg = "catalyrst-archipelago";
      port = 5139;
      extraPorts = [ ];
      subService = "comms";
      kind = "long-running";
      credFiles = [ "livekit-api.env" ];
      healthPath = "/ping";
      healthExpect = "2xx";
    };
    pulse = {
      bin = "catalyrst-pulse";
      pkg = "pulse";
      port = 7777;
      extraPorts = [ 5005 ];
      subService = "comms";
      kind = "long-running";
      credFiles = [ ];
      healthPath = null;
      healthExpect = null;
    };
    squid-eth = {
      bin = "squid-eth";
      pkg = "squid";
      port = 5131;
      extraPorts = [ ];
      subService = "squid";
      kind = "long-running";
      credFiles = [ "squid.env" ];
      healthPath = "/metrics";
      healthExpect = "any-http";
    };
    squid-polygon = {
      bin = "squid-polygon";
      pkg = "squid";
      port = 5132;
      extraPorts = [ ];
      subService = "squid";
      kind = "long-running";
      credFiles = [ "squid.env" ];
      healthPath = "/metrics";
      healthExpect = "any-http";
    };
    squid-migrate = {
      bin = "squid-migrate";
      pkg = "squid";
      port = null;
      extraPorts = [ ];
      subService = "squid";
      kind = "oneshot";
      credFiles = [ "squid.env" ];
      healthPath = null;
      healthExpect = null;
    };
    squid-search-path = {
      bin = null;
      pkg = null;
      port = null;
      extraPorts = [ ];
      subService = "squid";
      kind = "oneshot";
      credFiles = [ ];
      healthPath = null;
      healthExpect = null;
    };
    catalyrst-content-migrate = {
      bin = null;
      pkg = "catalyrst";
      port = null;
      extraPorts = [ ];
      subService = null;
      kind = "oneshot";
      credFiles = [ ];
      healthPath = null;
      healthExpect = null;
    };
    catalyrst-admin-secret = {
      bin = null;
      pkg = null;
      port = null;
      extraPorts = [ ];
      subService = null;
      kind = "oneshot";
      credFiles = [ ];
      healthPath = null;
      healthExpect = null;
    };
    catalyrst-world-storage-secret = {
      bin = null;
      pkg = null;
      port = null;
      extraPorts = [ ];
      subService = "worldStorage";
      kind = "oneshot";
      credFiles = [ ];
      healthPath = null;
      healthExpect = null;
    };
    postgresql-ownership = {
      bin = null;
      pkg = null;
      port = null;
      extraPorts = [ ];
      subService = null;
      kind = "oneshot";
      credFiles = [ ];
      healthPath = null;
      healthExpect = null;
    };
    postgresql-bundles = {
      bin = null;
      pkg = null;
      port = null;
      extraPorts = [ ];
      subService = null;
      kind = "oneshot";
      credFiles = [ ];
      healthPath = null;
      healthExpect = null;
    };
    livekit-rotate = {
      bin = null;
      pkg = null;
      port = null;
      extraPorts = [ ];
      subService = "comms";
      kind = "timer";
      credFiles = [ ];
      healthPath = null;
      healthExpect = null;
    };
    catalyrst-land-authz-index = {
      bin = "catalyrst-land-authz-index";
      pkg = "catalyrst-all";
      port = null;
      extraPorts = [ ];
      subService = "landAuthzIndex.enable";
      kind = "timer";
      credFiles = [ ];
      healthPath = null;
      healthExpect = null;
    };
    postgresql = {
      bin = "postgres";
      pkg = "nixpkgs.postgresql_18";
      port = 5432;
      extraPorts = [ ];
      subService = null;
      kind = "infra";
      credFiles = [ ];
      healthPath = null;
      healthExpect = null;
    };
    nginx = {
      bin = "nginx";
      pkg = "nixpkgs.nginx";
      port = 80;
      extraPorts = [ 443 ];
      subService = null;
      kind = "infra";
      credFiles = [ ];
      healthPath = null;
      healthExpect = null;
    };
  };

  services = {
    content = {
      unit = "catalyrst-sync";
      bundle = "core";
      bin = "catalyrst-live";
      port = 5141;
      subService = null;
      db = {
        name = "content";
        role = "catalyrst";
      };
      env = [
        {
          name = "SESSION_SECRET";
          secret = true;
          requiredAtBoot = true;
          autoGenerated = true;
        }
      ];
      healthPath = "/about";
      healthExpect = "2xx";
      serves = "catalyst content API + entity sync (content, lambdas, snapshots)";
    };
    sync = {
      unit = "catalyrst-sync";
      bundle = "core";
      bin = "catalyrst-live";
      port = 5141;
      subService = null;
      db = {
        name = "content";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = "/about";
      healthExpect = "2xx";
      serves = "entity-sync worker face of the content core (same module process as content)";
    };
    market = {
      unit = "catalyrst-data";
      bundle = "data";
      bin = "catalyrst-data";
      port = 5146;
      subService = "data";
      db = {
        name = "marketplace_squid";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "marketplace REST API over squid_marketplace";
    };
    economy = {
      unit = "catalyrst-data";
      bundle = "data";
      bin = "catalyrst-data";
      port = 5146;
      subService = "data";
      db = {
        name = "marketplace_squid";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "meta-tx relay / dapps API (reuses squid_marketplace)";
    };
    price = {
      unit = "catalyrst-data";
      bundle = "data";
      bin = "catalyrst-data";
      port = 5146;
      subService = "data";
      db = {
        name = "price";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "price estimation API";
    };
    credits = {
      unit = "catalyrst-data";
      bundle = "data";
      bin = "catalyrst-data";
      port = 5146;
      subService = "data";
      db = {
        name = "credits";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "marketplace credits";
    };
    places = {
      unit = "catalyrst-explore";
      bundle = "explore";
      bin = "catalyrst-explore";
      port = 5143;
      subService = "explore";
      db = {
        name = "places";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "places REST API";
    };
    events = {
      unit = "catalyrst-explore";
      bundle = "explore";
      bin = "catalyrst-explore";
      port = 5143;
      subService = "explore";
      db = {
        name = "places_events";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "events REST API";
    };
    worlds = {
      unit = "catalyrst-explore";
      bundle = "explore";
      bin = "catalyrst-explore";
      port = 5143;
      subService = "explore";
      db = {
        name = "worlds";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "World realm server API";
    };
    map = {
      unit = "catalyrst-explore";
      bundle = "explore";
      bin = "catalyrst-explore";
      port = 5143;
      subService = "explore";
      db = null;
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "atlas + satellite map tiles";
    };
    rpc = {
      unit = "catalyrst-data";
      bundle = "data";
      bin = "catalyrst-data";
      port = 5146;
      subService = "data";
      db = null;
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "generic JSON-RPC proxy member of the data bundle";
    };
    archipelago-api = {
      unit = "catalyrst-explore";
      bundle = "explore";
      bin = "catalyrst-explore";
      port = 5143;
      subService = "explore";
      db = null;
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "archipelago HTTP API surface in the explore bundle (the comms worker is the separate `archipelago` key)";
    };
    lists = {
      unit = "catalyrst-explore";
      bundle = "explore";
      bin = "catalyrst-explore";
      port = 5143;
      subService = "explore";
      db = null;
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "favorites / lists API";
    };
    builder = {
      unit = "catalyrst-create";
      bundle = "create";
      bin = "catalyrst-create";
      port = 5144;
      subService = "create";
      db = {
        name = "builder";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "Builder API";
    };
    camera-reel = {
      unit = "catalyrst-create";
      bundle = "create";
      bin = "catalyrst-create";
      port = 5144;
      subService = "create";
      db = {
        name = "camera_reel";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "camera reel (screenshot) storage API";
    };
    communities = {
      unit = "catalyrst-social";
      bundle = "social";
      bin = "catalyrst-social";
      port = 5145;
      subService = "social";
      db = {
        name = "communities";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "communities API (social-service-ea community routes)";
    };
    comms = {
      unit = "catalyrst-social";
      bundle = "social";
      bin = "catalyrst-social";
      port = 5145;
      subService = "social";
      db = {
        name = "comms";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "comms gatekeeper (livekit room grants)";
    };
    notifications = {
      unit = "catalyrst-social";
      bundle = "social";
      bin = "catalyrst-social";
      port = 5145;
      subService = "social";
      db = {
        name = "notifications";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "notifications feed + email confirmation";
    };
    badges = {
      unit = "catalyrst-social";
      bundle = "social";
      bin = "catalyrst-social";
      port = 5145;
      subService = "social";
      db = {
        name = "badges";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "achievement badges";
    };
    media = {
      unit = "catalyrst-social";
      bundle = "social";
      bin = "catalyrst-social";
      port = 5145;
      subService = "social";
      db = {
        name = "media";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "chat-translation proxy";
    };
    social-rpc = {
      unit = "catalyrst-social-rpc";
      bundle = "standalone";
      bin = "catalyrst-social-rpc";
      port = 5148;
      subService = "socialRpc";
      db = {
        name = "social_rpc";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
      serves = "social RPC (friends, blocks, private voice)";
    };
    explorer-api = {
      unit = "catalyrst-explorer-api";
      bundle = "standalone";
      bin = "catalyrst-explorer-api";
      port = 5137;
      subService = "explorerApi";
      db = null;
      env = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
      serves = "explorer bootstrap API (about, feature flags, auth)";
    };
    archipelago = {
      unit = "catalyrst-archipelago";
      bundle = "standalone";
      bin = "catalyrst-archipelago";
      port = 5139;
      subService = "comms";
      db = null;
      env = [
        {
          name = "LIVEKIT_API_KEY";
          secret = true;
          requiredAtBoot = true;
          autoGenerated = true;
        }
        {
          name = "LIVEKIT_API_SECRET";
          secret = true;
          requiredAtBoot = true;
          autoGenerated = true;
        }
      ];
      healthPath = "/ping";
      healthExpect = "2xx";
      serves = "archipelago comms orchestrator (island assignment over livekit)";
    };
    world-storage = {
      unit = "catalyrst-world-storage";
      bundle = "standalone";
      bin = "catalyrst-world-storage";
      port = 5154;
      subService = "worldStorage";
      db = {
        name = "worlds";
        role = "catalyrst";
      };
      env = [
        {
          name = "ENCRYPTION_KEY";
          secret = true;
          requiredAtBoot = true;
          autoGenerated = true;
        }
      ];
      healthPath = "/ping";
      healthExpect = "2xx";
      serves = "worlds content storage (uploads, ACLs)";
    };
    telemetry = {
      unit = "catalyrst-telemetry";
      bundle = "standalone";
      bin = "catalyrst-telemetry";
      port = 5150;
      subService = "telemetry";
      db = {
        name = "catalyrst";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = "/healthz";
      healthExpect = "2xx";
      serves = "telemetry ingest (sites TELEMETRY_URL sink)";
    };
    governance = {
      unit = "catalyrst-governance";
      bundle = "standalone";
      bin = "catalyrst-governance";
      port = 5151;
      subService = "governance";
      db = {
        name = "governance";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
      serves = "governance API (proposals, votes)";
    };
    presence = {
      unit = "catalyrst-presence";
      bundle = "standalone";
      bin = "catalyrst-presence";
      port = 5152;
      subService = "presence";
      db = {
        name = "presence";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
      serves = "user-count history";
    };
    signatures = {
      unit = "catalyrst-signatures";
      bundle = "standalone";
      bin = "catalyrst-signatures";
      port = 5159;
      subService = "signatures";
      db = {
        name = "signatures";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
      serves = "signature verification / delegation API";
    };
    profile-images = {
      unit = "catalyrst-profile-images";
      bundle = "standalone";
      bin = "catalyrst-profile-images";
      port = 5161;
      subService = "profileImages";
      db = null;
      env = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
      serves = "profile image render cache";
    };
    scene-state = {
      unit = "catalyrst-scene-state";
      bundle = "standalone";
      bin = "catalyrst-scene-state";
      port = 5209;
      subService = "sceneState";
      db = null;
      env = [ ];
      healthPath = "/ping";
      healthExpect = "2xx";
      serves = "authoritative scene-state server";
    };
    abgen = {
      unit = "catalyrst-ab-cdn";
      bundle = "standalone";
      bin = "abgen";
      port = 5147;
      subService = "abCdn";
      db = {
        name = "ab_registry";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
      serves = "JIT asset bundles + AB registry CDN";
    };
    sites = {
      unit = "catalyrst-sites";
      bundle = "standalone";
      bin = "sites-server";
      port = 5158;
      subService = "sites";
      db = null;
      env = [ ];
      healthPath = "/";
      healthExpect = "2xx";
      serves = "SSR web tier (react-router sites, /server operator page)";
    };
    opensea-resolver = {
      unit = "catalyrst-opensea-resolver";
      bundle = "standalone";
      bin = "opensea-resolver.mjs";
      port = 5162;
      subService = "gateway.enable";
      db = {
        name = "marketplace_squid";
        role = "catalyrst";
      };
      env = [ ];
      healthPath = "/health";
      healthExpect = "2xx";
      serves = "opensea metadata resolver for the gateway vhost";
    };
    squid-eth = {
      unit = "squid-eth";
      bundle = "standalone";
      bin = "squid-eth";
      port = 5131;
      subService = "squid";
      db = {
        name = "marketplace_squid";
        role = "squid";
      };
      env = [
        {
          name = "RPC_ENDPOINT_ETH";
          secret = true;
          requiredAtBoot = true;
        }
        {
          name = "DB_HOST";
          secret = false;
          requiredAtBoot = true;
        }
        {
          name = "DB_PORT";
          secret = false;
          requiredAtBoot = true;
        }
        {
          name = "DB_NAME";
          secret = false;
          requiredAtBoot = true;
        }
        {
          name = "DB_USER";
          secret = false;
          requiredAtBoot = true;
        }
        {
          name = "DB_PASS";
          secret = true;
          requiredAtBoot = true;
        }
        {
          name = "DB_SCHEMA";
          secret = false;
          requiredAtBoot = true;
        }
        {
          name = "SQD_PORTAL_URL";
          secret = false;
          requiredAtBoot = false;
        }
        {
          name = "SQD_PORTAL_API_KEY";
          secret = true;
          requiredAtBoot = false;
        }
      ];
      healthPath = "/metrics";
      healthExpect = "any-http";
      serves = "Subsquid ETH L1 processor filling squid_marketplace";
    };
    squid-polygon = {
      unit = "squid-polygon";
      bundle = "standalone";
      bin = "squid-polygon";
      port = 5132;
      subService = "squid";
      db = {
        name = "marketplace_squid";
        role = "squid";
      };
      env = [
        {
          name = "RPC_ENDPOINT_POLYGON";
          secret = true;
          requiredAtBoot = true;
        }
      ];
      healthPath = "/metrics";
      healthExpect = "any-http";
      serves = "Subsquid Polygon L2 processor filling squid_marketplace (shares squid.env with squid-eth)";
    };
    nginx-http = {
      unit = "nginx";
      bundle = "infra";
      bin = "nginx";
      port = 80;
      subService = null;
      db = null;
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "edge HTTP";
    };
    nginx-tls = {
      unit = "nginx";
      bundle = "infra";
      bin = "nginx";
      port = 443;
      subService = null;
      db = null;
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "edge TLS";
    };
    postgres = {
      unit = "postgresql";
      bundle = "infra";
      bin = "postgres";
      port = 5432;
      subService = null;
      db = null;
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "PostgreSQL cluster (module default 5432, overridable via pgPort)";
    };
    nats-client = {
      unit = "nats";
      bundle = "infra";
      bin = "nats-server";
      port = 4222;
      subService = "comms";
      db = null;
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "NATS client port";
    };
    nats-monitor = {
      unit = "nats";
      bundle = "infra";
      bin = "nats-server";
      port = 8222;
      subService = "comms";
      db = null;
      env = [ ];
      healthPath = "/varz";
      healthExpect = "any-http";
      serves = "NATS monitoring port";
    };
    libretranslate = {
      unit = "libretranslate";
      bundle = "infra";
      bin = "libretranslate";
      port = 5164;
      subService = "social";
      db = null;
      env = [ ];
      healthPath = "/languages";
      healthExpect = "2xx";
      serves = "LibreTranslate backend for the social bundle's /translate route";
    };
    livekit-signaling = {
      unit = "livekit";
      bundle = "infra";
      bin = "livekit-server";
      port = 7880;
      subService = "comms";
      db = null;
      env = [ ];
      healthPath = "/";
      healthExpect = "any-http";
      serves = "LiveKit signaling (ws)";
    };
    livekit-media-udp = {
      unit = "livekit";
      bundle = "infra";
      bin = "livekit-server";
      port = 7882;
      subService = "comms";
      db = null;
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "LiveKit media (udp)";
    };
    pulse = {
      unit = "pulse";
      bundle = "standalone";
      bin = "catalyrst-pulse";
      port = 7777;
      subService = "comms";
      db = null;
      env = [ ];
      healthPath = null;
      healthExpect = null;
      serves = "pulse UDP scene transport (tcp 5005 sidecar)";
    };
  };
}
