#!/usr/bin/env bash
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/_lib.sh"

MED_ENV="$ENV_DIR/catalyrst-media.env"

log "loading db credentials"
load_db_creds
set -a; source "$ENV_DIR/db.env"; set +a

if ! grep -q '^POSTGRES_CONTENT_USER=' "$ENV_DIR/content.env"; then
  warn "content DB credentials not in env/content.env -- bring up the content stack first"
  exit 1
fi
set -a; source "$ENV_DIR/content.env"; set +a

if ! pg_isready -h "$PG_SOCK_DIR" -p "$PG_PORT" -U "$POSTGRES_USER" >/dev/null 2>&1; then
  warn "postgres not running on $PG_SOCK_DIR:$PG_PORT -- start the database stack first."
  exit 1
fi

if ! grep -q '^POSTGRES_MEDIA_API_USER=' "$ENV_DIR/db.env"; then
  log "minting new catalyrst-media credentials"
  cat >> "$ENV_DIR/db.env" <<EOF

# catalyrst-media (added by bootstrap-catalyrst-media.sh)
POSTGRES_MEDIA_API_USER=med_$(openssl rand -hex 4)
POSTGRES_MEDIA_API_PASSWORD=$(openssl rand -hex 16)
EOF
  chmod 600 "$ENV_DIR/db.env"
  set -a; source "$ENV_DIR/db.env"; set +a
else
  log "reusing existing catalyrst-media credentials in db.env"
fi

export PGPASSWORD="$POSTGRES_PASSWORD"
PSQL=(psql -h "$PG_SOCK_DIR" -p "$PG_PORT" -U "$POSTGRES_USER" -v ON_ERROR_STOP=1 --no-psqlrc)

log "creating role $POSTGRES_MEDIA_API_USER if missing"
"${PSQL[@]}" -d postgres <<SQL
SELECT 'CREATE ROLE "$POSTGRES_MEDIA_API_USER" LOGIN PASSWORD ' || quote_literal('$POSTGRES_MEDIA_API_PASSWORD')
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$POSTGRES_MEDIA_API_USER')
\gexec
SQL

log "granting CRUD on translation_cache in content DB (table created by sqlx migration on boot)"
PGPASSWORD="$POSTGRES_CONTENT_PASSWORD" psql -h "$PG_SOCK_DIR" -p "$PG_PORT" \
  -U "$POSTGRES_CONTENT_USER" -d "$POSTGRES_CONTENT_DB" -v ON_ERROR_STOP=1 --no-psqlrc <<SQL
GRANT USAGE ON SCHEMA public TO "$POSTGRES_MEDIA_API_USER";
-- catalyrst-media runs sqlx migrate! on startup; pre-grant on the future table
-- via default privileges so the first boot can also SELECT/INSERT/UPDATE it.
ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_CONTENT_USER" IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$POSTGRES_MEDIA_API_USER";
-- and the schema-migrations bookkeeping table sqlx creates.
GRANT CREATE ON SCHEMA public TO "$POSTGRES_MEDIA_API_USER";
SQL

log "writing $MED_ENV"
DB_URL="postgresql:///$POSTGRES_CONTENT_DB?host=$PG_SOCK_DIR&port=$PG_PORT&user=$POSTGRES_MEDIA_API_USER&password=$POSTGRES_MEDIA_API_PASSWORD"
cat > "$MED_ENV" <<EOF
# auto-generated by scripts/bootstrap-catalyrst-media.sh -- do not commit

HTTP_SERVER_HOST=127.0.0.1
HTTP_SERVER_PORT=5143

MEDIA_PG_CONNECTION_STRING="$DB_URL"

# Translation backend: "mock" (echo/identity, dev) or "http" (LibreTranslate).
# Leaving TRANSLATE_BACKEND unset + a non-empty TRANSLATE_BACKEND_URL selects http.
TRANSLATE_BACKEND=mock
# TRANSLATE_BACKEND_URL=https://libretranslate.example.org
# TRANSLATE_BACKEND_API_KEY=

RUST_LOG=catalyrst_media=info,tower_http=info
EOF
chmod 600 "$MED_ENV"

log "bootstrap-catalyrst-media complete."
log "  next:  start the catalyrst-media service using your process manager of choice."
