#!/usr/bin/env node
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SITES = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REPO_ROOT = path.resolve(SITES, "..", "..");
const STORIES = path.join(SITES, "packages", "features", "src", "stories");

const specs: string[] = [];
(function walk(dir: string): void {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name === "story.md") specs.push(p);
  }
})(STORIES);
specs.sort();

let wrote = 0;
for (const md of specs) {
  const dir = path.dirname(md);
  const segments = path.relative(STORIES, dir).split(path.sep);
  const title = ["Sites Specs", ...segments].join("/");
  const repoRel = path
    .relative(REPO_ROOT, md)
    .split(path.sep)
    .join("/");

  const out = `// AUTO-GENERATED by catalyrst/sites/scripts/gen-spec-stories.mts -- edit story.md, then re-run.
import type { Meta, StoryObj } from "@ui/docs/sb";
import SpecDoc from "@ui/docs/SpecDoc";
import source from "./story.md?raw";

const meta = {
  title: ${JSON.stringify(title)},
  component: SpecDoc,
  tags: ["spec-doc"],
  parameters: {
    layout: "padded",
    a11y: { config: { rules: [{ id: "heading-order", enabled: false }] } },
  },
} satisfies Meta<typeof SpecDoc>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Spec: Story = {
  args: { source, path: ${JSON.stringify(repoRel)} },
};
`;

  const target = path.join(dir, "spec.stories.tsx");
  if (!existsSync(target) || readFileSync(target, "utf8") !== out) {
    writeFileSync(target, out);
    wrote += 1;
  }
}

console.log(`gen-spec-stories: ${specs.length} specs, ${wrote} files written`);
