#!/usr/bin/env node
// gen-story-id.mts -- derives the StoryId union from
// catalyrst/sites/packages/features/src/stories/**/story.md
// (the same set gen-spec-stories.mts turns into spec.stories.tsx pages) so a
// STORY constant citing a nonexistent spec fails typecheck instead of quietly
// tagging telemetry with a dead id.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SITES = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const STORIES = path.join(SITES, "packages", "features", "src", "stories");
const OUT = path.join(SITES, "packages", "core", "src", "lib", "telemetry", "story-id.ts");

const ids: string[] = [];
(function walk(dir: string): void {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name === "story.md") ids.push(path.relative(STORIES, dir).split(path.sep).join("/"));
  }
})(STORIES);
ids.sort();

const body = `// AUTO-GENERATED by catalyrst/sites/scripts/gen-story-id.mts -- edit stories/, then re-run.
export type StoryId =
${ids.map((id) => `  | ${JSON.stringify(id)}`).join("\n")};
`;

if (process.argv.includes("--check")) {
  const current = (() => {
    try {
      return readFileSync(OUT, "utf8");
    } catch {
      return null;
    }
  })();
  if (current !== body) {
    // The exit code turns on the whole body, never on the id diff below: a
    // header or ordering change is drift too, and must not be talked down to a
    // pass just because the id set happens to match.
    console.error("gen-story-id: packages/core/src/lib/telemetry/story-id.ts drifted from packages/features/src/stories/**/story.md");
    if (current === null) {
      console.error(`  ${path.relative(SITES, OUT)} does not exist`);
    } else {
      const committed = [...current.matchAll(/^\s*\| "([^"]+)"/gm)].map((m) => m[1]);
      const uncounted = ids.filter((id) => !committed.includes(id));
      const orphaned = committed.filter((id) => !ids.includes(id));
      for (const id of uncounted) console.error(`  story.md with no id in the union: ${id}`);
      for (const id of orphaned) console.error(`  id in the union with no story.md: ${id}`);
      if (uncounted.length === 0 && orphaned.length === 0)
        console.error("  the id set matches \u{2014} the generated body differs in header, order or formatting");
    }
    console.error("fix: cd catalyrst/sites && npm run gen:story-ids   # then commit the output");
    process.exit(1);
  }
  console.log(`gen-story-id: ${ids.length} story ids up to date`);
} else {
  writeFileSync(OUT, body);
  console.log(`gen-story-id: wrote ${ids.length} story ids to ${path.relative(SITES, OUT)}`);
}
