// The crate list the ts-rs/OpenAPI gate runs is DERIVED here from
// [package.metadata.generated] in each emitting crate's own Cargo.toml, so a
// crate can never fall off a hand-maintained list three areas away, and a
// reader inside the crate can see what it emits and which gate protects it.

import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const SITES = fileURLToPath(new URL("..", import.meta.url));
const ROOT = join(SITES, "..", "..");
const INDEX_REL = "catalyrst/ui3/src/generated/INDEX.json";
const CRATE_ROOTS = ["catalyrst/crates", "bevy-explorer/crates"];
const KINDS = ["ts-bindings", "openapi", "editor-bus"];

type Declared = Record<string, string>;

type Crate = {
  name: string;
  dir: string;
  manifest: string;
  declared: Declared | null;
  emitsTs: boolean;
  emitsOpenapi: boolean;
  exportDirs: string[];
};

type ArtefactRow = {
  artefact: string;
  kind: string;
  crate: string;
  manifest: string;
  gate?: string;
};

function tomlSection(text: string, header: string): Record<string, string> | null {
  const lines = text.split("\n");
  const start = lines.findIndex((l) => l.trim() === header);
  if (start < 0) return null;
  const out: Record<string, string> = {};
  for (let i = start + 1; i < lines.length; i++) {
    const t = lines[i]!.trim();
    if (t.startsWith("[")) break;
    const m = t.match(/^([A-Za-z0-9_-]+)\s*=\s*"([^"]*)"/);
    if (m) out[m[1]!] = m[2]!;
  }
  return out;
}

function rustSources(dir: string, out: string[] = []): string[] {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const e of entries) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) rustSources(p, out);
    else if (e.endsWith(".rs")) out.push(p);
  }
  return out;
}

function scanCrates(): Crate[] {
  const crates: Crate[] = [];
  for (const rootRel of CRATE_ROOTS) {
    const base = join(ROOT, rootRel);
    if (!existsSync(base)) continue;
    for (const name of readdirSync(base).sort()) {
      const manifest = join(base, name, "Cargo.toml");
      if (!existsSync(manifest)) continue;
      const text = readFileSync(manifest, "utf8");
      const pkg = tomlSection(text, "[package]");
      const declared = tomlSection(text, "[package.metadata.generated]");
      const src = join(base, name, "src");
      let emitsTs = false;
      let emitsOpenapi = false;
      const exportDirs = new Set<string>();
      for (const f of rustSources(src)) {
        const body = readFileSync(f, "utf8");
        if (body.includes("ts_rs::TS")) emitsTs = true;
        if (/\.openapi\.json"/.test(body)) emitsOpenapi = true;
        for (const m of body.matchAll(/export_to = "([^"]*)\/"/g)) exportDirs.add(m[1]!);
      }
      crates.push({
        name: pkg?.name ?? name,
        dir: `${rootRel}/${name}`,
        manifest: `${rootRel}/${name}/Cargo.toml`,
        declared,
        emitsTs,
        emitsOpenapi,
        exportDirs: [...exportDirs].sort(),
      });
    }
  }
  return crates;
}

function artefacts(crates: Crate[]): ArtefactRow[] {
  const rows: ArtefactRow[] = [];
  for (const c of crates) {
    const d = c.declared;
    if (!d) continue;
    for (const kind of KINDS) {
      const val = d[kind];
      if (!val) continue;
      // A value may hold several space-separated paths: one crate can emit
      // more than one binding dir (catalyrst-worlds exports worlds/ and
      // world-storage/), and TOML forbids repeating the key.
      for (const path of val.split(/\s+/).filter(Boolean)) {
        rows.push({ artefact: path, kind, crate: c.name, manifest: c.manifest, gate: d.gate });
      }
    }
  }
  rows.sort((a, b) => (a.artefact < b.artefact ? -1 : a.artefact > b.artefact ? 1 : 0));
  return rows;
}

function renderIndex(rows: ArtefactRow[]): string {
  return `${JSON.stringify(
    {
      note: `GENERATED by catalyrst/sites/scripts/generated-artefacts.mts from [package.metadata.generated] in each emitting crate. Do not edit. Regenerate: cd catalyrst/sites && npm run gen:artefacts`,
      artefacts: rows,
    },
    null,
    2,
  )}\n`;
}

function checkedCrateSet(crates: Crate[], key: string): string[] {
  return crates.filter((c) => c.declared?.[key]).map((c) => c.name);
}

function verify(crates: Crate[], rows: ArtefactRow[]): { errors: string[]; warnings: string[] } {
  const errors: string[] = [];
  const warnings: string[] = [];

  for (const c of crates) {
    const d = c.declared;
    if (c.emitsTs && !d?.["ts-bindings"] && !d?.["editor-bus"]) {
      errors.push(
        `${c.manifest}: crate derives ts_rs::TS but declares no [package.metadata.generated] ts-bindings \u{2014} its bindings are generated and checked by nothing`,
      );
    }
    if (c.emitsOpenapi && !d?.openapi) {
      errors.push(
        `${c.manifest}: crate writes an *.openapi.json spec but declares no [package.metadata.generated] openapi`,
      );
    }
    if (!d) continue;
    if (!d.gate) errors.push(`${c.manifest}: [package.metadata.generated] has no gate key`);
    for (const k of Object.keys(d)) {
      if (k !== "gate" && !KINDS.includes(k)) {
        errors.push(`${c.manifest}: unknown [package.metadata.generated] key "${k}"`);
      }
    }
    if (d["ts-bindings"] && !c.emitsTs) {
      errors.push(`${c.manifest}: declares ts-bindings but no source derives ts_rs::TS`);
    }
    if (d.openapi && !c.emitsOpenapi) {
      errors.push(`${c.manifest}: declares openapi but no source writes an *.openapi.json spec`);
    }
    if (d["ts-bindings"] && c.exportDirs.length > 0) {
      // export_to paths are relative to the area's export root (the generated
      // root for the bridge, generated/catalyst for catalyrst crates) and may be
      // nested (webbridge/hostbridge), so strip the root rather than basenaming.
      const declaredDirs = [d["ts-bindings"], d["editor-bus"] ?? ""]
        .join(" ")
        .split(/\s+/)
        .filter(Boolean)
        .map((p) => p.replace(/^.*\/src\/generated\/(catalyst\/)?/, "").replace(/\.ts$/, ""))
        .sort();
      if (declaredDirs.join(" ") !== c.exportDirs.join(" ")) {
        errors.push(
          `${c.manifest}: declares ts-bindings dirs "${declaredDirs.join(" ")}" but the crate exports to "${c.exportDirs.join(" ")}"`,
        );
      }
    }
    if (d.gate && !existsSync(join(ROOT, d.gate))) {
      errors.push(`${c.manifest}: gate "${d.gate}" does not exist`);
    }
  }

  const declaredPaths = new Set(rows.map((r) => r.artefact));
  const catalystDir = join(ROOT, "catalyrst/ui3/src/generated/catalyst");
  for (const e of readdirSync(catalystDir)) {
    const p = join(catalystDir, e);
    if (!statSync(p).isDirectory() || e === "openapi") continue;
    const rel = relative(ROOT, p);
    if (!declaredPaths.has(rel)) {
      errors.push(`${rel}: committed generated bindings that no crate declares \u{2014} nothing regenerates them`);
    }
  }
  const openapiDir = join(catalystDir, "openapi");
  for (const e of readdirSync(openapiDir)) {
    if (!e.endsWith(".openapi.json")) continue;
    const rel = relative(ROOT, join(openapiDir, e));
    if (!declaredPaths.has(rel)) {
      errors.push(`${rel}: committed OpenAPI spec that no crate declares \u{2014} nothing regenerates it`);
    }
  }

  for (const r of rows) {
    if (!existsSync(join(ROOT, r.artefact))) {
      warnings.push(
        `${r.artefact}: declared by ${r.crate} but not committed \u{2014} ${r.gate} will report it as drift (fix: cd catalyrst/sites && npm run gen:types)`,
      );
    }
  }
  return { errors, warnings };
}

const crates = scanCrates();
const rows = artefacts(crates);
const mode = process.argv[2] ?? "--check";

if (mode === "--list") {
  const what = process.argv[3] ?? "";
  const lists: Record<string, string[]> = {
    "catalyrst-pkgs": crates
      .filter((c) => c.dir.startsWith("catalyrst/crates/") && c.declared)
      .map((c) => c.name),
    "catalyrst-ts": crates
      .filter((c) => c.dir.startsWith("catalyrst/crates/") && c.declared?.["ts-bindings"])
      .map((c) => c.name),
    "catalyrst-openapi": crates
      .filter((c) => c.dir.startsWith("catalyrst/crates/") && c.declared?.openapi)
      .map((c) => c.declared!.openapi!.replace(/^.*\//, "").replace(/\.openapi\.json$/, ""))
      .sort(),
    bridge: checkedCrateSet(
      crates.filter((c) => c.dir.startsWith("bevy-explorer/crates/")),
      "ts-bindings",
    ),
  };
  if (!lists[what]) {
    console.error(`usage: generated-artefacts.mts --list <${Object.keys(lists).join("|")}>`);
    process.exit(2);
  }
  console.log(lists[what].join("\n"));
  process.exit(0);
}

if (mode === "--write") {
  writeFileSync(join(ROOT, INDEX_REL), renderIndex(rows));
  console.log(`generated-artefacts: wrote ${rows.length} entries to ${INDEX_REL}`);
  process.exit(0);
}

if (mode !== "--check") {
  console.error("usage: generated-artefacts.mts [--check|--write|--list <name>]");
  process.exit(2);
}

const { errors, warnings } = verify(crates, rows);
const committedIndex = existsSync(join(ROOT, INDEX_REL))
  ? readFileSync(join(ROOT, INDEX_REL), "utf8")
  : "";
if (committedIndex !== renderIndex(rows)) {
  errors.push(`${INDEX_REL}: stale (fix: cd catalyrst/sites && npm run gen:artefacts)`);
}

for (const w of warnings) console.error(`generated-artefacts: WARNING ${w}`);
if (errors.length > 0) {
  console.error("generated-artefacts: FAILED");
  for (const e of errors) console.error(`  ${e}`);
  process.exit(1);
}
console.log(
  `generated-artefacts: OK (${rows.length} artefacts declared by ${crates.filter((c) => c.declared).length} crates${warnings.length ? `, ${warnings.length} warning(s)` : ""})`,
);
