#!/usr/bin/env bash
# catalyrst init -- scaffold a starter host configuration by asking the few
# things the module cannot default: domain, profile, how TLS is issued, and
# the external RPC endpoints. Writes a `catalyrst-host.nix` module and prints
# the exact remaining steps (secrets, DNS, rebuild). Wired as `nix run .#init`.
set -euo pipefail

ask() { # prompt default -> echoes the answer
  local prompt="$1" default="${2:-}" reply
  if [ -n "$default" ]; then
    read -rp "$prompt [$default]: " reply || true
    printf '%s' "${reply:-$default}"
  else
    read -rp "$prompt: " reply || true
    printf '%s' "$reply"
  fi
}

echo "-- catalyrst node scaffolder ------------------------------------------"
echo "Answers become a catalyrst-host.nix you import into your NixOS config."
echo

DOMAIN="$(ask 'Domain (the realm is served here, e.g. realm.example.org)')"
[ -n "$DOMAIN" ] || { echo "A domain is required." >&2; exit 1; }

echo
echo "Profile:"
echo "  1) content-node    content API + sync only, LAN/dev, plain HTTP"
echo "  2) full-realm      a playable realm: content + comms + the bundle tier"
echo "  3) public-gateway  a full public node with every surface (default)"
case "$(ask 'Choice' 3)" in
  1) PROFILE=content-node ;;
  2) PROFILE=full-realm ;;
  *) PROFILE=public-gateway ;;
esac

OUT="$(ask 'Write the host module to' './catalyrst-host.nix')"

# Per-profile extras.
TLS_BLOCK="" RPC_BLOCK="" ADMIN_BLOCK="" NOTES=()
if [ "$PROFILE" = content-node ]; then
  NOTES+=("Serves plain HTTP on :80 to the LAN -- no TLS, no DNS records needed.")
else
  echo
  echo "TLS / certificate issuance:"
  echo "  1) acme-dns01   ONE wildcard DNS record (*.$DOMAIN), needs a DNS-provider API token (default)"
  echo "  2) acme-http01  no token, but one A-record per subdomain (~29), each must resolve first"
  if [ "$(ask 'Choice' 1)" = 2 ]; then
    TLS_BLOCK=$'\n    tls = "acme-http01";'
    NOTES+=("acme-http01: create an A-record for $DOMAIN AND every subdomain the gateway serves; run 'nixos-rebuild' only after they resolve.")
  else
    PROVIDER="$(ask 'DNS provider (lego name: cloudflare, route53, gcloud, digitalocean, ...)' 'cloudflare')"
    TLS_BLOCK=$'\n    tls = "acme-dns01";\n    dnsProvider = "'"$PROVIDER"'";'
    NOTES+=("acme-dns01: create ONE wildcard record  *.$DOMAIN -> this host.")
    NOTES+=("Put your $PROVIDER API token in  <secretsDir>/acme-dns.env  (the variables lego expects).")
  fi

  ADMIN="$(ask 'Admin wallet address (0x..., gates /admin and /server; blank to skip)')"
  [ -n "$ADMIN" ] && ADMIN_BLOCK=$'\n    adminAddresses = [ "'"$ADMIN"'" ];'

  ETH="$(ask 'Ethereum mainnet RPC URL (head-state calls; the indexer has its own archive RPCs)' 'https://rpc.decentraland.org/mainnet')"
  RPC_BLOCK=$'\n    ethRpcUrl = "'"$ETH"'";'
  NOTES+=("squid indexer (marketplace): write <secretsDir>/squid.env before first boot with RPC_ENDPOINT_ETH + RPC_ENDPOINT_POLYGON (archive nodes, e.g. https://eth.drpc.org + https://polygon.drpc.org) and SQD_PORTAL_API_KEY (free key: https://www.sqd.ai). Or set subServices.squid = false.")
fi

cat > "$OUT" <<EOF
# Generated by \`nix run .#init\`. Import this into your host configuration and
# pass the flake's inputs through specialArgs = { inherit inputs; }.
{ ... }:
{
  services.catalyrst = {
    enable = true;
    profile = "$PROFILE";
    domain = "$DOMAIN";$TLS_BLOCK$ADMIN_BLOCK$RPC_BLOCK
    # Every *Package option defaults to the flake's own build; the firewall
    # opens the node's own ports (openFirewall = true). Override as needed.
  };
}
EOF

echo
echo "-- wrote $OUT ---------------------------------------------------------"
echo "Next steps:"
i=1
for n in "${NOTES[@]}"; do echo "  $i. $n"; i=$((i + 1)); done
echo "  $i. Import $OUT into a NixOS host (with inputs.catalyrst.nixosModules.catalyrst)."
echo "  $((i + 1)). nixos-rebuild switch  --  auto-minted secrets (admin/livekit/world-storage) generate on first boot."
echo "  $((i + 2)). Verify:  curl -s http://<host>/about | jq .content.healthy"
