// AUTO-GENERATED by catalyrst/sites/scripts/gen-spec-stories.mts -- edit story.md, then re-run.
import type { Meta, StoryObj } from "@ui/docs/sb";
import SpecDoc from "@ui/docs/SpecDoc";
import source from "./story.md?raw";

const meta = {
  title: "Sites Specs/misc/jump-in",
  component: SpecDoc,
  tags: ["spec-doc"],
  parameters: {
    layout: "padded",
    a11y: { config: { rules: [{ id: "heading-order", enabled: false }] } },
  },
} satisfies Meta<typeof SpecDoc>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Spec: Story = {
  args: { source, path: "catalyrst/sites/packages/features/src/stories/misc/jump-in/story.md" },
};
